/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package Lab1;

public class Library {
	public static void main(String arg[]) {
		System.out.println("When you have a fire, commit and push.");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
